#!/bin/bash

if [ ${BUILDKITE_PLUGIN_KIND_CLUSTER_DEBUG_PLUGIN:-false} == "true" ]; then
	set -eux
else
	set -eu
fi

echo "--- :k8s: Determining Node Image"

if [ ! -z ${BUILDKITE_PLUGIN_KIND_CLUSTER_CUSTOM_IMAGE:-} ]; then
	export IMAGE=${BUILDKITE_PLUGIN_KIND_CLUSTER_CUSTOM_IMAGE}
else
	case ${BUILDKITE_PLUGIN_KIND_CLUSTER_K8S_VERSION:-1.29} in
	1.29)
		export IMAGE=kindest/node:v1.29.1@sha256:aa49c4486220dc6b4ea7749407fb2ab95a50fdea155e760b3589a2a4699c0741
  		;;
	1.28)
		export IMAGE=kindest/node:v1.28.6@sha256:299852461cfe4b68212b479557cdcf1d059ce2394631814b41b5ddf6eb71fff4
  		;;
	1.27)
		export IMAGE=kindest/node:v1.27.10@sha256:b43f97a57f658b447543fb900741b461f3565634d6cc3c16a60755030c5edd18
  		;;
	*)
		echo "ERROR: Unsupported Version: $BUILDKITE_PLUGIN_KIND_CLUSTER_K8S_VERSION"
		echo "ERROR: Kind Cluster Buildkite Plugin supports versions: 1.29, 1.28 and 1.27"
		exit 1
		;;
        esac

fi

if [ ! -z ${BUILDKITE_PLUGIN_KIND_CLUSTER_CONFIG_PATH:-} ];then
	echo "--- :k8s: Setting KinD Config Path"
	export CONFIG=" --config ${BUILDKITE_PLUGIN_KIND_CLUSTER_CONFIG_PATH} "
fi

echo "--- :k8s: Setting Cluster Name"
export CLUSTER_NAME=buildkite-${BUILDKITE_STEP_ID:-000}

echo "--- :bash: Setting local bin path"
export LOCAL_BIN=~/.local/bin
mkdir -p $LOCAL_BIN
export PATH=$PATH:$LOCAL_BIN
