#!/bin/bash

if [ ${BUILDKITE_PLUGIN_KIND_CLUSTER_DEBUG_PLUGIN:-false} == "true" ]; then
	set -eux
else
	set -eu
fi

echo "--- :k8s: Determining Node Image"

if [ ! -z ${BUILDKITE_PLUGIN_KIND_CLUSTER_CUSTOM_IMAGE:-} ]; then
	export IMAGE=${BUILDKITE_PLUGIN_KIND_CLUSTER_CUSTOM_IMAGE}
else
	case ${BUILDKITE_PLUGIN_KIND_CLUSTER_K8S_VERSION:-1.22} in
	1.23)
		export IMAGE=kindest/node:v1.23.5@sha256:a69c29d3d502635369a5fe92d8e503c09581fcd406ba6598acc5d80ff5ba81b1
  		;;
	1.22)
		export IMAGE=kindest/node:v1.22.7@sha256:c195c17f2a9f6ad5bbddc9eb8bad68fa21709162aabf2b84e4a3896db05c0808
		;;
	1.21)
		export IMAGE=kindest/node:v1.21.10@sha256:f35554e42a1081cfc9f7bce5635aea15996e4ec842b689e1508a8746de7d309b
  		;;
	1.20)
		export IMAGE=kindest/node:v1.20.15@sha256:2d93744654696ea4270c04ec83e7940177295aac99223b224b052c79d4e7693e
  		;;
	*)
		echo "ERROR: Unsupported Version: $BUILDKITE_PLUGIN_KIND_CLUSTER_K8S_VERSION"
		echo "ERROR: Kind Cluster Buildkite Plugin supports versions: 1.23, 1.22, 1.21 and 1.20"
		exit 1
		;;
        esac

fi

if [ ! -z ${BUILDKITE_PLUGIN_KIND_CLUSTER_CONFIG_PATH:-} ];then
	echo "--- :k8s: Setting KinD Config Path"
	export CONFIG=" --config ${BUILDKITE_PLUGIN_KIND_CLUSTER_CONFIG_PATH} "
fi

echo "--- :k8s: Setting Cluster Name"
export CLUSTER_NAME=buildkite-${BUILDKITE_STEP_ID:-000}
