#!/bin/bash

if [ ${BUILDKITE_PLUGIN_KIND_CLUSTER_DEBUG_PLUGIN:-false} == "true" ]; then
        set -eux
else
        set -eu
fi

echo "--- :k8s: Installing KinD"
curl -Lo ./kind "https://kind.sigs.k8s.io/dl/v0.21.0/kind-linux-amd64"
chmod +x ./kind

echo "--- :k8s: Creating Cluster - ${CLUSTER_NAME}"
./kind create cluster --name ${CLUSTER_NAME} --image ${IMAGE} ${KIND_CONFIG:-} --wait 2m

echo "--- :k8s: Setting Kubeconfig"
./kind export kubeconfig --name ${CLUSTER_NAME} --kubeconfig ./kubeconfig-${CLUSTER_NAME}
export KUBECONFIG=$(pwd)/kubeconfig-${CLUSTER_NAME}
